("a number of","いくつもの ；かなり多くの"),
("a piece of","１つ［１個；１本；１枚；...］の"),
("a couple of","２つの ；２人の ／２，３の"),
("a great [good] deal of","かなりたくさん の"),
("plenty of","たくさんの"),
("dozens of","何ダースもの ；数十もの"),
("close to","のすぐ近くに；ほぼ"),
("these days","近ごろは；このごろは"),
("and so on [forth]","など"),
("all over","の 至る所に［で］／一面に"),
("so far","今までのところ"),
("far from","どころではない； からほど遠い"),
("all the time","いつも；常に"),
("first of all","まず第一に"),
("be likely to do","しそうである"),
("be different from","とは違っている"),
("be aware of","に気がついている； を知っている"),
("be responsible for","に責任がある"),
("be willing to do","してもかまわない"),
("be afraid of","を恐れる［怖がる］； を心配している"),
("be about to do","今にも しようとしている"),
("be capable of","ができる； の可能性がある"),
("be based on [upon]","に基づいている"),
("be made of","で成り立っている"),
("be satisfied with","に満足している"),
("lead to","へ通じる； を引き起こす"),
("come from","の出身である； から生じる； に由来する"),
("depend on [upon]","に頼る； 次第である"),
("think of","のことを考える； しようかなと思う／ を思いつく／ を思い出す"),
("refer to","に言及する／ を参照する； に問い合わせる"),
("look for","を探す"),
("grow up","大人になる； 事態などが 生じる"),
("focus on","に焦点を合わせる； に集中する"),
("deal with","を扱う； を処理する"),
("contribute to","に貢献する； に寄付［寄稿］する"),
("fill out","書類など に書き込む"),
("result in","に終わる"),
("rely on [upon]","に頼る"),
("get to","に到着する／ するようになる； できる"),
("suffer from","病気など に悩む； で苦しむ"),
("work on","働き続ける／ を製作する； に取り組む； に影響を与える"),
("care for","の世話をする／ を好む； を望む"),
("consist of","から成り立っている"),
("ask for","を求める"),
("go through","を通過する／ 苦しみなど を経験する"),
("turn out","であることがわかる； 結果的に になる／ を産出する／ 催しなどに 繰り出す"),
("search for","を捜［探］す"),
("participate in","に参加する"),
("concentrate on","に集中する"),
("care about","を気にかける； に関心を持つ"),
("hear of","のこと［噂・消息］を聞く"),
("believe in","を信用する； の良さ［存在］を信じる"),
("complain about [of]","について不平を言う； 苦痛など を訴える"),
("succeed in","に成功する"),
("call for","を必要とする； を求める／ 人 を誘い［迎え］に行く； 物 を取りに行く"),
("look after","の世話をする"),
("get along","暮らす； なんとか やっていく／ と 仲良くやっていく with ； が 進む with"),
("differ from","と異なる"),
("hear from","から便り［電話・伝言］がある"),
("result from","から起こる"),
("try on","を試着する"),
("pick up","を拾う； を 車などに 乗せる"),
("give up","をあきらめる； を捨てる［やめる］"),
("set up","を立［建］てる； を創設する； を始める"),
("wake up","目が覚める； 人 の目を覚まさせる"),
("bring up","を育てる／ 問題・話題など を持ち出す"),
("break up","を 解散［散会・解体］させる［する］ 関係などが 終わる； 人が 別れる； を終わらせる"),
("find out","調査などの結果 を見つけ出す； 真相 を知る"),
("point out","を指摘する"),
("figure out","を理解する； を計算する； を解く"),
("carry out","を実行する"),
("put on","を 身に 付ける； 電気器具・ガスなど をつける"),
("get on","公共の乗り物など に乗る／ なんとか やっていく； と 仲良くやっていく with"),
("carry on","を続ける"),
("cut down [back] on","の 消費 量を減らす； を切り詰める"),
("break down","を破壊する； を取り壊す； を分解する／故障する；取り乱す；肉体的［精神的］に参る"),
("bring about","を引き起こす"),
("take off","を脱ぐ； を取りはずす／離陸する； 流行・売り上げなどが 急増［急伸］する"),
("leave behind","を置いていく； を置き忘れる"),
("for example [instance]","例えば"),
("in fact","実際に／ ところが 実際は"),
("at home","在宅して；家庭で／くつろいで／ に 精通して in ；on ；with"),
("in the future","将来は；今後は"),
("after all","結局 は ；やっぱり"),
("at first","最初は"),
("on the other hand","これに反して；他方では"),
("in other words","言い換えれば；つまり"),
("in general","一般に／一般の"),
("for the first time","初めて"),
("in turn","順々に； 立ち代わって 次に は"),
("by the way","ところで"),
("in particular","特に"),
("for a while","しばらくの間"),
("in time","に 間に合って for ／やがて；そのうちに"),
("in the end","ついには；結局は"),
("at once","すぐに／同時に"),
("at work","仕事中で［の］；職場で／運転［作動］中で［の］；作用して"),
("on time","時間どおりに［で］"),
("in part","一部には；いくぶん かは"),
("as a whole","全体として の"),
("agree with","人が人・考えなど に同意する； 気候・食物などが に合う； に一致［適合］する"),
("at a time","１度に"),
("not always","必ずしも ではない"),
("as as possible [one can]","できる限り"),
("at the most","多くても；せいぜい"),
("look forward to","を楽しみに待つ"),
("take care of","の世話をする； に気をつける"),
("take place","起こる；催される"),
("play a role [part] in","で 役割を演じる［果たす］"),
("make sure","を 確かめる；確実に する"),
("make sense","意味をなす；道理にかなう"),
("pay attention to","に注意を払う"),
("at all","全く／一体；そもそも／せっかく；とにかく"),
("make a difference","違いが生じる；重要である"),
("have an influence [effect] on","に影響を与える"),
("come up with","解決策など を思いつく； 案など を提出する"),
("make a mistake","間違いをする"),
("do one's best","最善を尽くす"),
("change one's mind","気［考え］が変わる"),
("make an effort [efforts]","努力する"),
("come true","夢・予言などが 実現する"),
("get lost","道に迷う"),
("used to do [be]","したものだった；昔は であった"),
("at times","ときどき"),
("had better do","したほうがいい； すべきだ"),
("enjoy oneself","楽しい時を過ごす"),
("see A as B","AをBと見なす"),
("provide A with B","AにBを供給する"),
("prevent A from B","AをBから防ぐ；Aを妨げてBをさせない"),
("spend A on B","AをBに使う"),
("share A with B","AをBと分け合う［共有する］"),
("help A with B","AをBで助ける"),
("think of A as B","AをBと見なす"),
("regard A as B","AをBと見なす"),
("in short","つまり；短く言えば"),
("turn A into B","AをBに 質的に 変える"),
("describe A as B","AをBと述べる；AをBに分類する"),
("associate A with B","AをBと結びつけて考える"),
("devote A to B","AをBにささげる"),
("according to","によれば／ に従って； に応じて"),
("because of","のために"),
("instead of","の代わりに； しないで"),
("in front of","の前に［で］"),
("as a result of","の 結果として"),
("in addition to","に 加えて；さらに"),
("along with","と一緒に； に加えて"),
("on earth","一体全体／世界中で"),
("thanks to","のおかげで"),
("regardless of","に関係なく； に も かかわらず"),
("in contrast to [with]","と 対照して； と 著しく違って"),
("in spite of","にもかかわらず"),
("apart from","のほかに／ を除いては"),
("as if [though] ...","まるで...のように"),
("in case ...","もし...ならば／...するといけないから；...に備えて"),
("B as well as A","AだけではなくBも"),
("not A but B","AではなくB"),
("at least","少なくとも"),
("not only A but also B","AだけではなくBも"),
("call off","を中止する； を取り消す"),
("catch up with [to]","に追いつく"),
("come about","起こる"),
("come by","を手に入れる"),
("do away with","を廃止する； を取り除く"),
("find fault with","にけちをつける； を非難する"),
("get over","病気など から回復する； を克服する"),
("get rid of","やっかいな物 を取り除く"),
("hand in","手渡しで を提出する"),
("as usual","いつものように"),
("learn by heart","を暗記する"),
("look into","を調べる"),
("look over","を ざっと 調べる"),
("make up one's mind","決心する"),
("pass away","死ぬ"),
("pick out","を選ぶ"),
("put off","を延期する"),
("put up with","を我慢する"),
("set about","を始める"),
("set in","主に気候・病気などが 始まる"),
("at best","よくても；せいぜい"),
("stand up for","を支持［擁護］する"),
("take after","に似ている"),
("think over","をよく考える"),
("turn in","を提出する； を引き渡す［返却する］"),
("all of a sudden","突然に；不意に"),
("before long","間もなく"),
("by degrees","徐々に"),
("by no means","全然 ない"),
("every now and then [again]","ときどき；ときおり"),
("every once in a while","ときどき；ときおり"),
("for good","永久に"),
("no longer","もはや ない"),
("from time to time","ときどき；ときおり"),
("in advance","前もって"),
("in all","全部で"),
("of importance","重要な；重要性のある"),
("on purpose","わざと；故意に"),
("over and over again","何度も繰り返し"),
("prior to","より前で"),
("right away","直ちに；今すぐ"),
("agree to","に同意する"),
("apply for","（仕事・許可など）を申し込む；を志願［申請］する"),
("all in all","概して；全体的には"),
("anything but","全然ではない；どころではない"),
("apply to","に当てはまる／（人・場所・組織）に申し込む"),
("as a matter of course","当然［もちろん］のこととして"),
("as a matter of fact","実際は；実を言うと"),
("as for","について言えば；に関する限り"),
("as to","に関して（は）"),
("at a distance","ある距離を置いて"),
("at any rate","とにかく；いずれにしても"),
("at present","現在は；目下"),
("at the moment","現在は"),
("be anxious about","を心配している"),
("be anxious to do","したがる"),
("be apt to do","しがちである"),
("be bound for","行きである"),
("be bound to do","きっとする"),
("be concerned about [for]","を心配している"),
("be concerned with [in]","に関係している"),
("be equal to","に等しい"),
("be equivalent to","に等しい"),
("be essential to","にとって不可欠である"),
("be familiar to","（人）によく知られている"),
("be familiar with","（物事）をよく知っている"),
("be free from [of]","がない"),
("be free to do","自由にする"),
("be inclined to do","する傾向がある；したい気がする"),
("be indispensable to [for]","にとって不可欠である"),
("be sure [certain] to do","きっとする"),
("be sure of [about]","を確信している"),
("be tired from [with]","で疲れる"),
("be tired of","に飽きる；にうんざりしている"),
("be true of","に当てはまる"),
("be true to","に忠実である"),
("by accident","偶然に"),
("by chance","偶然に"),
("catch sight of","を見つける［見かける］"),
("cling to","に固執［執着］する；にくっつく"),
("compensate for","の埋め合わせをする；を補償する"),
("consist in","にある"),
("correspond to","に相当する；に該当する"),
("correspond with","と文通する"),
("date back to","にさかのぼる；に始まる"),
("date from","から始まる；から続いている"),
("distinguish A from B","AをBと区別する"),
("each other","お互い"),
("for all","にもかかわらず"),
("for now","当分は；今のところは"),
("for one's own part","としては；に関する限りは"),
("for the time being","差し当たり；当分の間（は）"),
("give in to","（に）屈服する"),
("give way to","（に）屈する；（に）道を譲る"),
("hit on [upon]","を思いつく；に出くわす"),
("hold back","を制止する；（真相など）を隠す"),
("in a word","要するに；つまり"),
("in any case [event]","とにかく；いずれにしても"),
("in brief","要するに；つまり"),
("in the air","空中で［の］；（雰囲気などが）感じられて"),
("in the distance","遠方に；遠くで"),
("in the way of","（の）邪魔になって"),
("keep back","を制止する；（真相など）を隠す"),
("keep pace with","に遅れずについていく"),
("keep up with","に遅れずについていく"),
("lay off","を一時解雇する"),
("lay out","を設計する；を並べる"),
("let alone","は言うまでもなく"),
("lie in","にある"),
("look down on [upon]","を軽べつする"),
("lose sight of","を見失う"),
("major in","（学生が）を専攻する"),
("make the best of","を最大限に利用する"),
("make the most of","を最大限に利用する"),
("make up for","の埋め合わせをする；を補償する"),
("mistake A for B","AをBと間違える"),
("not to mention","は言うまでもなく"),
("nothing but","ただだけ；にすぎない"),
("occur to one","ふと（人）の心に浮かぶ"),
("on account of","のために"),
("on and off","断続的に"),
("on and on","どんどん；延々と"),
("on one's part","の側での；のほうでは"),
("on the air","放送中の"),
("on the contrary","それどころか；それに反して"),
("on the way to","（への）途中で"),
("on the whole","概して；全体的には"),
("one another","お互い"),
("owing [due] to","のために"),
("put aside","を取っておく；を脇に置く；を蓄える"),
("set aside","を取っておく；を脇に置く；を蓄える"),
("sit up","（寝ないで）起きている／（寝た状態から）上半身を起こす／きちんと座る"),
("specialize in","を専攻する；を専門にする"),
("stand out","目立つ；際立つ"),
("stay up","（寝ないで）起きている"),
("stick out","突き出る；目立つ"),
("stick to","にくっつく；（主義・決定など）を堅持する"),
("take A for B","AをBだと（誤って）思う；AをBと間違える"),
("tell A from B","AをBと区別する"),
("to the contrary","それと反対の［に］"),
("with all","にもかかわらず"),
("yield to","に屈する；に道を譲る"),
("above all else","とりわけ；特に"),
("act on","～に作用する；～に働きかける／ 命令・信念など に従って行動する"),
("all the same","それでもやはり"),
("all at once","突然に／すべて同時に"),
("all but","～も同然；ほとんど～／～以外すべて"),
("all the way","はるばる；ずっと"),
("as a general rule","概して；普通 は"),
("as well","～もまた"),
("at a glance","ひと目見て"),
("at large","全体としての；一般の／逃走中で；逮捕されないで"),
("at length","詳細に；長々と／とうとう；ついに"),
("at random","手当たり次第に；無作為に"),
("back and forth","前後［左右］に；行ったり来たり"),
("be due to","～のため［結果］である／～する予定である"),
("break in","押し入る；口を挟む／～を慣らす"),
("break out","火事・戦争などが 起こる／ 吹き出もの・汗などが 出る；急に ～ し出す"),
("by all means","ぜひとも；必ず／ぜひどうぞ"),
("by hand","手で；手を使って"),
("by mistake","間違って"),
("by now","今ごろは；今はもう"),
("by way of","～経由で／～として；～のつもりで の"),
("call on","～を訪問する／～に要求する"),
("come to","～に来る；～に達する／～するようになる／意識を回復する；正気に戻る"),
("for so long","大変に［そんなに］ 長時間"),
("for one thing","１つには"),
("for the most part","大部分は；大体は"),
("from onward","～から以後は"),
("from point of view","～の視点から は"),
("give out","～を配る；～を発する／ 供給物・力などが 尽きる；なくなる"),
("go by","時などが たつ；通り過ぎる／～の名で通る［知られる］；～によって行動［判断］する"),
("go off","去る； 電灯などが 消える／ 仕掛けが 作動する； 爆薬が 爆発する； 銃などが 発射され"),
("go over","～を調べる；～に詳細に目を通す／～を復習する；～を繰り返す"),
("go with","～と付き合う／～に似合う"),
("hold on","持ちこたえる；頑張る／待つ；電話を切らずにいる／ ～を しっかりつかむ to ～"),
("hold out","手など を差し出す／持ちこたえる；耐える； 希望など を抱く"),
("hold up","～を持ち上げる／～を遅らせる／～に強盗に入る"),
("in sight","見えて；視界に入って"),
("in a hurry","急いで；あせって"),
("in a sense","ある意味では；ある程度"),
("in detail","詳細に"),
("in effect","事実上；要するに／ 法律などが 実施されて"),
("in one's opinion [view]","～の意見では"),
("in practice","実際には"),
("in private","ひそかに；秘密に"),
("in public","人前で；公然と"),
("in reality","想像などでなく 実際に； ところが 実際には"),
("in the first place","まず第一に"),
("in the meantime [meanwhile]","その間に も ；一方 話変わって"),
("in theory","理論上は"),
("live on","～を常食にする／ ～の収入・金額 で生活する／生き続ける"),
("look out for","～に 気をつける／ ～の 世話をする； ～の 面倒を見る"),
("look to","～のほうを見る；～に気をつける／～に頼る；～を当てにする"),
("look up","辞書・電話帳などで ～を調べる／ 人 を訪ねる"),
("make for","～のほうへ進む／～に寄与する；～に役立つ"),
("make out","～を理解する／～を見分ける／ 書類・小切手など を作成する"),
("meet with","～を経験する；～を受ける／～と約束して会う；～と会見する"),
("most of all","とりわけ；何［誰］よりもまず"),
("next to","～の次の［に］／ほとんど～"),
("on the average","平均して"),
("on end","連続して／まっすぐに"),
("out of date","時代遅れの"),
("out of sight","見えない所に 法外な 際立っている"),
("provide for","～を扶養する／～に備える； 法律が ～を規定する"),
("pull up","～を引き抜く［引き上げる］；～を根絶する／ 車などを 止める；止まる"),
("put down","～を置く／～を抑える；～を鎮める"),
("put out","火・明かりなど を消す／～を出す"),
("put up","～を掲げる；～を上げる；～を建てる／～を泊める；泊まる"),
("run across","～に偶然出会う；～を偶然見つける／～を走って横切る"),
("run over","車が ～をひく／ ～から あふれる"),
("set out","出発する／ ～し 始める to do"),
("settle down","落ち着く；定住する／腰を据えて～を し 始める to ～ / to do"),
("show up","予定の所に 現れる／～を目立たせる；目立つ"),
("sort of","なんとなく ～ ；ちょっと ～"),
("stand by","待機する；傍観する／～を支持［擁護］する； 約束など を守る"),
("stand for","～を意味する；～の略字である／ 主義など を支持する"),
("take in","～を取り入れる；～を理解する／～をだます／～を見物する"),
("take on","～を引き受ける；～を雇う／ 色・性質など を帯びる"),
("take one's place","いつもの席に着く；特定の地位を占める／～に取って代わる"),
("take to","習慣的に ～を始める；～にふける／～を好きになる"),
("take up","場所・時間 を取る； を取り上げる／ 仕事・趣味など を始める"),
("to extent [degree]","～の程度に"),
("to one's surprise","～が驚いたことに"),
("turn down","～を拒絶する；～を却下する／ 音量・火力など を小さくする"),
("turn over","ページなど をめくる；～をひっくり返す；ひっくり返る／～を譲る；～を引き渡す"),
("turn up","現れる；起こる／ ガス・音量など を大きくする；～を探し出す"),
("up to","～まで／～次第である；～の責任である／～をしようとして"),
("up to date","最新 式 の"),
("upside down","逆さまに；ひっくり返って"),
("at one's ease","くつろいで"),
("be dependent on","～に依存している"),
("be independent of","～から独立している"),
("catch on","ファッション・考えなどが 流行する；はやる／ ～を 理解する to ～ ； ～に 気づく"),
("ill at ease","不安で；落ち着かないで"),
("in order","整頓されて；順調で"),
("later on","後で"),
("look up to","～を尊敬する"),
("make up","～を作り上げる；～を構成する／ ～と 仲直りさせる［する］ with ～ ／～の埋め合わせを"),
("out of order","故障して；順序が狂って"),
("turn off","スイッチなど を消す； 水・ガスなど を止める； 明かりなどが 消える"),
("turn on","スイッチなど をつける； 水・ガスなど を出す； 明かりなどが つく"),
("hand in hand with","（～と）手を携えて；相伴って"),
("add to","～を増す"),
("adhere to","～にくっつく ；（主義・規則など）に固執する［を守る］"),
("aim at","～を狙う；～を目指す"),
("amount to","総計～になる"),
("apologize to A for B","(Bのことで） A （人）に謝る"),
("approve of","～を承認する；～に賛成する"),
("at any cost [all costs]","ぜひとも"),
("become of","～はどうなるか"),
("blame A for B","BをAのせいにする；BのことでAを非難する"),
("blow up","爆発する；かっとなる；～を爆破する"),
("break into","～に侵入する／急に～し出す"),
("break off","（～を）急にやめる；～を切り離す"),
("bring back","～を返す；～を思い出させる"),
("bring out","～を出す；～を明らかにする"),
("burn down","（建物が）全焼する；～を全焼させる"),
("burst into","急に～し出す；突然～に入る"),
("call up","（～に）電話をかける；（記憶・勇気など）を呼び起こす"),
("cheer up","元気づく；～を元気づける；～を応援する"),
("clear up","（天候が）晴れる；（疑念・不明点など）を明らかにする"),
("coincide with","～と一致する；～と同時に起こる"),
("come across","～に偶然出会う；～を偶然見つける／（考えなどが相手に）伝わる；理解される"),
("come out","現れる；ばれる；出版される"),
("compete with","～と競争する"),
("conform to [with]","～に合わせる；～に従う"),
("count on [upon]","～に頼る；～を当てにする"),
("decide on [upon]","～を決める；～に決める"),
("die of [from]","～で死ぬ"),
("die out","絶滅する；（習慣などが）すたれる"),
("dispose of","～を処分する；～を平らげる"),
("do with","～を処理［処置］する／～を済ませた；～と縁を切った"),
("do without","なしで済ます"),
("drop in","ちょっと立ち寄る"),
("drop out","脱落する；中途退学する"),
("end up","最後には～になる"),
("end with [by]","～で終わる"),
("enter into","～に参加する；～を始める"),
("exchange A for B","AをBと交換する"),
("fall on [upon]","（休日などが）～に当たる；（責任・仕事などが）～に降りかかる"),
("feed on","～を常食［餌］にする"),
("get at","～に達する；～を手に入れる／～をほのめかす"),
("get through","～を（し）終える／（電話などが）通じる；連絡がつく"),
("get together","集まる；～を集める"),
("give away","～をただでやる；～を配る；（秘密など）を漏らす"),
("give off","（光・音・においなど）を発する"),
("go about","～に精を出す；～に取り掛かる"),
("graduate from","～を卒業する"),
("hand down","～を子孫［後世］に伝える"),
("hang up","電話を切る；～を中断する；（壁などに）～を掛ける"),
("head for","～に向かう"),
("hurry up","急ぐ；～を急がせる"),
("insist on [upon]","～を主張する"),
("interfere with","～を妨げる；～の邪魔をする"),
("iron out","（問題など）を解決［調整］する"),
("keep off","～に近寄らない；～に触れない；～を慎む"),
("keep to","～に従う；～から脱線しない"),
("leave out","～を省く；～を入れずにおく"),
("little by little","少しずつ"),
("long for","～を切望する"),
("look back on [upon]","～を回顧する；～を追想する"),
("no doubt","たぶん ；おそらく"),
("object to","～に反対する"),
("on the spot","その場で；即座に"),
("once upon a time","昔々"),
("one by one","１つずつ；１人ずつ"),
("part with","（物）を（しぶしぶ）手放す"),
("pass by","（～のそばを）通り過ぎる；素通りする；（時が）過ぎる"),
("pass on","（物・情報など）を次に回す；～を伝える"),
("prepare for","～の準備をする；～に備える"),
("put away","～を片づける；～を取っておく；～を捨てる"),
("put together","（部品など）を組み立てる；（考えなど）をまとめる"),
("recover from","～から立ち直る；～から回復する"),
("reflect on [upon]","～を熟考［反省］する"),
("refrain from","～を慎む"),
("resort to","（手段など）に訴える；～に頼る"),
("rest on [upon]","～に頼る；～次第である"),
("run into","～にぶつかる；～に偶然出会う；～を偶然見つける"),
("run out of","～を使い果たす"),
("send for","（人）を呼びにやる；（物）を取りにやる"),
("set down","～を書き留める；～を決める"),
("set off","出発する；～を引き起こす"),
("show off","（～を）見せびらかす"),
("shut up","話をやめる；～を黙らせる"),
("side by side with","（～と）肩を並べて；（～と）協力［共存］して"),
("sign up for","（署名して）（～に）加わる；（受講などの）届け出をする"),
("slow down","（～の）速度を落とす；速度が落ちる"),
("sooner or later","遅かれ早かれ"),
("step by step","一歩ずつ；着実に"),
("step up","（壇上などに）上がる；近づく／（量・速度など）を増す；～を促進する"),
("substitute A for B","Bの代わりに (Aを）使う"),
("sum up","（～を）要約する；～を合計する"),
("sympathize with","～に同情する"),
("take away","～を持ち去る；～を取り除く"),
("take down","～を書き留める；（建物など）を取り壊す"),
("take over","（～を）引き継ぐ；～を支配する"),
("throw away","～を捨てる"),
("use up","～を使い果たす"),
("wear out","すり減る；～をすり減らす［疲れ果てさせる］"),
("wish for","～を望む［願う］；～を欲しがる"),
("forgive A for B","BのことでAを許す"),
("close [near] at hand","近くで［に］"),
("accuse A of B","BのことでAを非難［告訴］する"),
("adapt A to [for] B","AをBに合うように変える；AをBに適合させる"),
("assure A of B","A（人）にB（物・事）を請け合う［保証する］"),
("at a loss","途方に暮れて；困って；損をして"),
("at first sight","一見したところでは；ひと目で［の］"),
("at risk","危険な状態で"),
("at the cost of","～を犠牲にして"),
("at the expense of","～を犠牲にして"),
("at the mercy of","～のなすがままになって"),
("at the sight of","～を見て"),
("attach A to B","AをBに取りつける［付与する］"),
("attribute A to B","AをBのせいにする"),
("be absorbed in","～に熱中している"),
("be abundant in","～が豊富である"),
("be accustomed to","～に慣れている"),
("be acquainted with","～と知り合いである；～に精通している"),
("be ashamed of","～を恥じている"),
("be characteristic of","～に特有である；いかにも～らしい"),
("be composed of","～から構成されている"),
("be conscious of","～を意識している；～に気づいている"),
("be content [contented] with","～に満足している"),
("be contrary to","～に反している"),
("be engaged in","～に従事している；忙しく～している"),
("be entitled to","～の［～する］資格がある"),
("be equipped with","～を備えている"),
("be faced with [by]","（人が）（災害など）に直面している"),
("be grateful to A for B","Bのことで (Aに）感謝している"),
("be guilty of","～を犯している；～で有罪である"),
("be ignorant of","～を知らない"),
("be involved in","～に関係［関与］している；～に携わっている；～に熱中している"),
("be lacking in","～に欠けている"),
("be open to","～に開かれている"),
("be opposed to","～に反対している"),
("be particular about [over]","～について気難しい［やかましい］"),
("be peculiar to","～に特有である"),
("be popular with [among]","～に人気がある"),
("be related to","～と関係がある；～と姻戚関係がある"),
("be sensitive to","～に敏感である"),
("be similar to","～に似ている"),
("be subject to","～を受けやすい；～に服従している"),
("be superior to","～より優れている"),
("be tolerant of","～に対して寛大である"),
("be typical of","～に特有である；～に典型的である"),
("be versed in","～に精通［熟達］している"),
("be well off","裕福である"),
("be worried about [over]","～のことで心配している"),
("be worthy of","～に値する；～にふさわしい"),
("clear A of B","AからBを取り除く"),
("compare A with [to] B","AをBと比較する；AをBにたとえる"),
("confine A to B","AをBに限定する；AをBに閉じ込める"),
("congratulate A on B","BのことでAを祝う"),
("convince A of B","A（人）にB（事）を納得［確信］させる"),
("cure A of B","AのBを治す［取り除く］"),
("deprive A of B","AからBを奪う"),
("derive A from B","BからAを引き出す"),
("expose A to B","AをBにさらす"),
("furnish A with B","AにBを供給する［備えつける］"),
("impose A on [upon] B","AをBに課する［押しつける］"),
("in the face of","～に直面して；～にもかかわらず"),
("in the light of","～から見て；～を考慮して"),
("in a way","ある点で；ある意味では"),
("in charge of","～を預かって；～を管理して"),
("in connection with","～に関連して；～と共同で"),
("in danger of","危険で；（～の）危険があって"),
("in demand","需要があって；必要とされて"),
("in exchange for","（～と）交換に"),
("in fashion","流行して"),
("in favor of","～に賛成して；～のほうを選んで"),
("in harmony with","～と調和［一致］して"),
("in honor of","～に敬意を表して；～のために"),
("in need of","～を必要として"),
("in place of","～の代わりに"),
("in pursuit of","～を追求して"),
("in relation to","～に関連して（の）；～と比べて"),
("in return for","（～の）お返しに；（～と）引き換えに"),
("in search of","～を探して"),
("in terms of","～の観点から；～に換算して"),
("in the course of","～の間［うち］に"),
("in the long run","結局は；長い目で見れば"),
("in the presence of","～のいる所［面前］で；～を目の前にして"),
("in view of","～を考慮して"),
("inform A of [about] B","AにBを知らせる"),
("keep A from B","AをBから防ぐ；Aを妨げてBをさせない"),
("leave A up to B","AをBに任せる；AをBに残す"),
("name A after B","AをBにちなんで名づける"),
("owe A to B","AをBに借りている；A（恩・義務など）をBに負っている"),
("prefer A to B","BよりAを好む"),
("present A with B","AにBを贈る［与える］"),
("prohibit A from B","AがB（するの）を禁止する［妨げる］"),
("put into practice [operation]","～を実行［実施］する"),
("remind A of B","AにBを思い出させる"),
("rob A of B","（暴力・脅迫などで） AからBを奪う"),
("stop A from B","AにBをさせない"),
("strike A as B","A（人）にBの印象を与える"),
("supply A with B","AにBを供給する"),
("suspect A of B","BについてAを疑う"),
("talk A into B","A（人）を説得してBをさせる"),
("transform A into [to] B","AをBに変える［変質させる］"),
("on a basis","～の基準［原則］で"),
("a bit of","少量の～；一片の～"),
("a handful of","一握りの～；少数［量］の～"),
("a host of","多数の～"),
("a variety of","（同一種類のもので）いろいろな～；さまざまな～／～の一種類［型］"),
("against one's will","意志に反して；心ならずも"),
("ahead of","～の先に；～より進んで；（時間的に）～より先に"),
("as opposed to","～とは対照的に；～ではなく"),
("aside from","～を除いては；～のほかに"),
("ask one a favor","（人）に願い事を頼む"),
("be forced to do","やむなく～する"),
("be reluctant to do","～したがらない"),
("be supposed to do","～することになっている；（世間で）～と考えられている"),
("behind the times","時代遅れの"),
("but for","～がない［なかった］ならば"),
("by means of","～によって；～を用いて"),
("by virtue of","～のおかげで；～によって"),
("catch one doing","(人）が～しているところを見つける［捕らえる］"),
("come into [in] contact with","～と接触する；～に会う"),
("come into being [existence]","出現する；生まれ出る"),
("compared with [to]","～と比べると"),
("do one good","（人）に利益を与える；（人）のためになる"),
("except for","～を除いて；～以外は；～がない［なかった］ならば"),
("fail to do","～し損なう ；～できない"),
("fall in love with","～と恋に落ちる；～が大好きになる"),
("find one's way to","～まで道を探しながら進む；～へたどり着く"),
("for fear of","～を恐れて"),
("for lack [want] of","～がないために；～の不足のために"),
("for the benefit of","～のために"),
("for the sake of","～のために"),
("generally speaking","一般的に言えば"),
("give birth to","～を生［産］む；～の原因になる"),
("give rise to","～を引き起こす；～を生む"),
("go on doing","～し続ける"),
("happen to do","偶然～する"),
("have in mind","～のことを考えている"),
("have A in common with B","（Bと）共通にAを持っている"),
("have difficulty in doing","～するのが困難である；苦労しながら～する"),
("in order [so as] to do","～するために"),
("judging from [by]","～から判断すると"),
("keep [bear] in mind","～を心にとどめておく；～を忘れない"),
("keep [stay] in touch with","～と連絡を取り合っている；（最新情報など）に通じている"),
("keep an eye on","～から目を離さない；～を見張る"),
("keep doing","～し続ける"),
("keep one's word [promise]","約束を守る"),
("leave alone","～をそのままにしておく；～に干渉しない"),
("live [lead] a life","～の生活をする"),
("make a [one's] living","生計を立てる"),
("make friends with","～と親しくなる"),
("make fun of","～をからかう"),
("make it","うまくやる；成功する；間に合う；出席する"),
("make one's way to","（～に向かって）進む"),
("make progress","進歩する"),
("make use of","～を利用する"),
("manage to do","なんとか～する［やり遂げる］"),
("needless to say","言うまでもなく"),
("on one's guard","警戒して"),
("on [in] behalf of","～のために；～を代表して"),
("on a scale","（～な）規模で［の］"),
("on board","（乗り物）に乗って"),
("on duty","当番で；勤務時間中で"),
("on the increase","増加中で"),
("out of control","制御できない"),
("out of hand","手に負えない；即座に"),
("out of the question","不可能で；あり得ない"),
("place emphasis on [upon]","～を強調する"),
("remember to do","忘れずに～する"),
("set free","～を自由の身にする"),
("shake hands with","（～と）握手する"),
("so to speak","いわば"),
("so A as to do","～するほどAである／非常にAなので～する"),
("speaking [talking] of","～と言えば"),
("take a chance","危険を冒す；思い切ってやってみる；（～に）賭ける (on ～)"),
("take a risk [risks]","（あえて）危険を冒す"),
("take advantage of","～を利用する；～につけ込む"),
("take part in","～に参加する"),
("take pride in","～を誇る；～を自慢に思う"),
("tend to do","～しがちである；～する傾向がある"),
("to be sure","確かに"),
("to begin [start] with","まず第一に；最初に［は］"),
("to make matters worse","さらに悪いことに"),
("to say nothing of","～は言うまでもなく"),
("to the point","適切な；要を得た"),
("without fail","必ず；間違いなく"),
("will do","～は役に立つ；～は用が足りる"),
("as is often the case with","（～に関して）よくあることだが"),
("be to do","～することになっている／～すべきである／～できる"),
("be used to doing","～することに慣れている"),
("be worth doing","～する価値がある"),
("cannot too ...","いくら～してもしすぎることはない"),
("cannot help but do","～せざるを得ない；～せずにはいられない"),
("cannot help doing","～せざるを得ない；～せずにはいられない"),
("feel like doing","～したい気がする"),
("may well do","おそらく～するだろう；～しても不思議ではない"),
("might just as well do","（気は進まないがどうせなら）～するほうがいい；～してもよい；～するのも同じだ"),
("no matter how","どんなに～でも"),
("remember doing","～したのを覚えている"),
("when it comes to doing","～する問題になると"),
("with a view to doing","～する目的で"),
("would rather than ...","（...するより）むしろ～したい"),
("all the＋比較級＋for","～のためますます...；～のためそれだけいっそう..."),
("as as any ＋名詞","誰［どれ］にも劣らず～な"),
("as as ever","相変わらず～な"),
("as good as","～も同然；ほとんど～"),
("as much [many] as","～もの数の；～と同数の"),
("at one's best","最も良い状態で［の］"),
("what A is","現在のA"),
("what is more","さらに；それに"),
("what we call","いわゆる～"),
("all by oneself","他人から離れてひとりぼっちで／他人の力を借りずに独力で"),
("enough to go around","物が出席者などの全員に行き渡る"),
("in the way","Sが～するやり方で"),
("It is No wonder that","...なのは当然だ"),
("It is True , but","確かに～であるが，...だ"),
("Just As , so","ちょうど～であるように，..."),
("The Chances are that","ひょっとしたら...だろう；たぶん...だろう"),
("The Fact is that","実は...である"),
("The Point is that","大事な点は...だ；要するに..."),
(", so that","～だ，その結果...だ"),
("A is one thing; B is another","AとBとは別のものである"),
("A is to B what C is to D","AのBに対する関係はCのDに対する関係に等しい"),
("All one has to do is to do","ただ～すればよい"),
("and yet","それにもかかわらず"),
("as [so] far as be concerned","～に関する限り"),
("as [so] long as","...である限り［間］は；...でありさえすれば"),
("as far as","...までも／...する限りでは"),
("as it is","実際のところは／事物があるがままの［に］"),
("as it were","いわば"),
("be all the rage","大流行［ブーム］になっている"),
("be all ears","一心に耳を傾けている"),
("be crazy about","～に夢中である；～が大好きである"),
("be cut out for","～に向いて［生まれついて］いる"),
("be fed up with","～にうんざりしている"),
("be to blame for","～に対して責めを負うべきである［責任がある］"),
("bring oneself to do","～する気持ちになる"),
("by far","はるかに；ずっと"),
("by the time","Sが～するまでには"),
("call back","～を呼び戻す；～に折り返し電話する；後で～に電話をかけ直す"),
("call it a day","その日の仕事を終える"),
("calm down","落ち着く；～を落ち着かせる；静まる；～を静める"),
("can afford to do","経済的・時間的に ～する余裕がある"),
("check out","～を調査［点検］する／図書館などから～を借り出す"),
("come close [near] to doing","もう少しで～しそうになる"),
("Couldn't be better.","これ以上の良さはあり得ない。；最高です。"),
("drop one a line","人に短い手紙を書く；人に一筆書く"),
("either A or B","AかBかどちらか"),
("every [each] time","...するたびに"),
("for a rainy day","将来のまさかの時［緊急時］に備えて"),
("for oneself","他人に頼らないで自分で；自分自身のために"),
("go so far as to do","～しさえする"),
("hardly when [before]","～するかしないうちに..."),
("have no other choice but to do","～するよりほかに仕方がない"),
("have something to do with","～と関係がある"),
("if any","もしあれば；もしあるとしても"),
("if it were not for","もし～がなければ"),
("if only","...でありさえすれば／...でさえあればなあ"),
("in itself","それ自体では；本来は"),
("in that","...のゆえに；...の点で"),
("It follows that","当然...ということになる"),
("It goes without saying that","...なのは言うまでもない"),
("It is about time that","ほぼ...してよいころである"),
("It is no use doing","～しても無駄である"),
("It is not until that","～して初めて...する"),
("know better than to do","～するほどばかなことはしない；～しないだけの分別がある"),
("leave nothing to be desired","申し分ない"),
("more of a A than B","BというよりA"),
("more often than not","普通は；たいてい"),
("more or less","ほぼ；いくぶん；多かれ少なかれ"),
("much [still] less","まして～はいっそうない"),
("never without","～すれば必ず...する"),
("no less A than B","Bに劣らずA；B同様にA"),
("no less than","～も；～と同様に"),
("no more A than B","Bと同様にAでない"),
("no more than","わずか～だけ ；～にすぎない"),
("no sooner A than B","AするやいなやBする"),
("not in the least","全く～ない"),
("not so much A as B","AというよりB"),
("Nothing is more A than B","BほどAなものはない"),
("now that","今はもう...なので；...である以上"),
("on the condition that","...という条件で；...ならば"),
("on the grounds that","...という根拠［理由］で"),
("one , the other","２つのうちで一方は～，もう一方は..."),
("one after another","次々に"),
("pride oneself on","～を誇る；～を自慢に思う"),
("provided that","もし...ならば"),
("remain to be seen","結果などは未定である"),
("see to it that","...するように取り計らう［気をつける］"),
("so that A will do","Aが～するように"),
("spend time in doing","～して時間・期間を過ごす"),
("stand to reason","もっともである；理屈に合う"),
("take for granted","～を当然のことと思う"),
("take seriously","～を真剣に受け止める"),
("take the trouble to do","労を惜しまず～する；わざわざ～する"),
("that is to say","つまり；すなわち"),
("the former , the latter","前者は～で，後者は..."),
("the last to do","最も～しそうでない..."),
("the moment [minute]","...するとすぐに"),
("the＋比較級, the＋比較級","～であればあるほど，いっそう...である"),
("There is no doing","～することはできない"),
("for free","無料で；ただで"),
("just around the corner","（距離・時間的に）すぐ近くに"),
("to death","死ぬまで～；ひどく～"),
("to go","あと～；残りの～；持ち帰り用の～"),
("abide by","（法・約束など）に従う［を守る］"),
("account for","～の理由を説明する；～の説明となる／（割合など）を占める"),
("allow for","～を考慮に入れる；～を見込む"),
("ascribe A to B","AをBのせいにする"),
("aspire to","（大きな目標の達成など［～すること］）を熱望する"),
("attend to","～に注意を払う；～の世話をする；～を処理する"),
("boast of [about]","～を自慢する；～を誇らしげに話す"),
("break the ice","（会合などの初めの）緊張をほぐす；話の口火を切る"),
("bring A home to B","A（ある事柄）をB（人）に痛感させる"),
("come down with","（病気）にかかる"),
("come of age","（法律的に）成人に達する"),
("come to an end [a close]","終わる"),
("come to light","明るみに出る；現れる"),
("come to terms with","～と折り合いがつく；（あきらめて）～を受け入れる"),
("comply with","（規則・命令など）に従う；～に応じる"),
("cope with","～に対処する；～をうまく処理する"),
("deal in","（商品）を商う；（仕事など）に従事する"),
("dispense with","～なしで済ます"),
("do justice","～を正当に評価する；（写真などが）～を実物どおりに表す"),
("dwell on [upon]","～を詳しく論じる［述べる；書く］／～にこだわる；～をくよくよ［つくづく］考え"),
("embark on [upon]","（事業・計画など）に乗り出す；～を始める"),
("fall back on [upon]","（最後の手段として）～に頼る"),
("fall short of","～に達しない"),
("find oneself","（気がついてみると）（人が）～にいる；～である；～とわかる"),
("follow suit","先例に従う；人のまねをする"),
("for sure [certain]","確かに（は）"),
("get [have] the better of","～に勝つ；～を出し抜く"),
("get down to","（仕事・問題など）に本気で取り掛かる"),
("get even with","（人）に仕返しをする；（人）に恨みを晴らす"),
("get on A's nerves","Aの神経にさわる"),
("give A credit for B","A（人）をB（事柄）のことで称賛する［認める］"),
("give one a hand","（人）に手を貸す"),
("give one's regards to","（人）によろしくとのあいさつを伝える"),
("go a long way towards","（～に）大いに役立つ"),
("go ahead","先に行く；進む"),
("go out of one's way to do","わざわざ［故意に］～する"),
("hand over","～を引き渡す；～を手渡す"),
("hang on","持ちこたえる；電話を切らずにおく；しがみつく"),
("have [take] a look at","（～を）見る"),
("have a good [great] time","楽しい時を過ごす"),
("have a sweet tooth","甘いものが好きだ；甘党だ"),
("have an eye for","～に対する眼識［鑑識力］がある"),
("have no idea","見当がつかない"),
("have yet to do","これから～しなければならない；まだ～していない"),
("having said that [so]","そうは言ったものの"),
("help oneself to","～を自由に取る"),
("Here we are.","さあ着いたぞ。"),
("hold one's breath","息を止める；【通常否定文で】（期待して）息をひそめる"),
("hold the line","電話を切らずにそのまま待つ"),
("hold true","当てはまる；有効である"),
("How about ?","～はいかがですか。"),
("How come ?","どうして (～) 。"),
("in no time","瞬く間に；あっという間に"),
("indulge in","（快楽など）にふける；思う存分～する"),
("let down","～を失望させる"),
("let go of","（～を）手放す；（～を）捨てる"),
("live up to","（期待など）に添う；～に恥じない行動をする；（義務など）を果たす"),
("make believe that","（...という）ふりをする"),
("make do with","（代用品などで）間に合わせる"),
("make good","成功する／（約束など）を果たす；（損害など）を償う"),
("make oneself understood","自分の言うことを相手にわからせる"),
("miss out on","（好機など）を逃す；～を取り逃がす"),
("My pleasure.","どういたしまして。"),
("pass out","気絶する；酔いつぶれる"),
("persist in","～に固執する；～を主張する"),
("pull A's leg","A（人）をかつぐ；A（人）をからかう"),
("range from A to B","AからBに及ぶ"),
("read between the lines","行間を読む；暗黙のうちに理解する"),
("rise [get] to one's feet","立ち上がる"),
("rule out","（可能性など）を排除する；～を認めない"),
("see off","（人）を見送る"),
("settle for","（不十分ながら）～で我慢する"),
("single out","～を選び出す"),
("Something is wrong with .","～はどこか調子がおかしい［故障している］。"),
("speak ill of","～の悪口を言う"),
("speak out [up]","はっきり［思い切って］話す"),
("such as it is","これだけの［つまらない］ものですが"),
("take it easy","のんびりと構える"),
("take one's time","時間をかけてゆっくりやる；自分のペースでやる"),
("tear down","（建物）を取り壊す；～を打ち砕く"),
("tell on [upon]","～に（悪く）影響する；～にこたえる"),
("think better of","～を見直す；～を考え直してやめる"),
("think much [highly] of","～を尊敬［尊重］する；～を高く評価する"),
("think twice","よく考える；考え直す"),
("throw up","～を投げ（上げ）る；～をさっと上げる／（食べた物を）吐く"),
("watch one's step","足元に注意する；慎重に行動する"),
("watch out for","（～に）気をつける"),
("What for?","どうして...。；何の目的で...。"),
("What like?","～はどんなものか。"),
("What a shame!","なんて残念な［気の毒な］。"),
("What do you say to doing?","～するのはどうですか。"),
("What if ?","もし...ならどうするか。"),
("What's up?","何かあったのですか。；どうしたのですか。"),
("Why not?","それいいね。；ぜひそうしよう。"),
("work out","～を作り出す；～を解決する；～の答えを出す；（計画が）うまくいく／運動する"),
("yearn for","～にあこがれる；～を恋しがる"),
("You're kidding me.","冗談でしょう。；まさか。"),
("all on one's own","（すべて）自分１人で；（すべて）独力で"),
("at first hand","直接に；じかに"),
("of one's own","自分自身の～"),
("all along","最初からずっと"),
("all too","とても；非常に"),
("as follows","次のとおり"),
("as of","～現在で；～の時点で"),
("as such","そういうものとして；それ自体"),
("at [on] short notice","急に；即座に"),
("at A's convenience","Aの都合の良いときに"),
("at A's disposal","Aの自由になって；Aが自由に使えて"),
("at heart","心の底では；根は；本当は"),
("at issue","論争中の［で］；問題の"),
("at one's wit's end","途方に暮れて"),
("at stake","危うくなった［なって］；賭けられた［られて］"),
("at will","思いのままに；随意に"),
("be beside oneself with","（～で）我を忘れる；（～に）夢中である"),
("be crucial to","～にとって重要である"),
("be indifferent to","～に無関心［平気］である"),
("be intent on [upon]","～に懸命である；～に熱心である"),
("be keen on","～に熱心である；～が大好きである"),
("be liable to","～しがちである；～にかかりやすい"),
("be second to none","誰［何物］にも劣らない；最高である"),
("be susceptible to","～の影響を受けやすい；～に感染しやすい"),
("behind A's back","Aのいない所で"),
("beyond description","言葉では表現できないほどの［に］"),
("beyond the reach of","～の（手が）届かない所に"),
("by and large","概して"),
("by nature","生まれつき；元来"),
("down the road","やがては；将来は"),
("early on","早い時期に；早くから"),
("even as","まさに...している［していた］ときに"),
("every other","１つ［１日；１週；...］おきの［に］～／残りのすべての～"),
("for all I know","よくは知らないが，たぶん"),
("for nothing","無料で／無駄に"),
("if anything","どちらかと言えば；もしあるとしても"),
("in a row","連続して"),
("in accordance with","～に従って；～に応じて"),
("in comparison with [to]","（～と）比較すれば"),
("in due course [time]","やがて；そのうち"),
("in earnest","熱心に；本格的に"),
("in good shape","調子が良くて"),
("in person","（代理人でなく）本人が；自ら"),
("in proportion to","～に比例して"),
("in store for","（～のために）用意して；（～の身に）降りかかろうとして"),
("in the works","準備中で；計画［開発］中で"),
("keep company","～と一緒にいる；～に付き合う"),
("keep in check","～を抑える；～を食い止める"),
("keep to oneself","～を人に話さないでおく；～を占有する"),
("keep track of","～の跡をたどる；（記録するなどして）～を忘れないようにする"),
("know by sight","（人）の顔は見て知っている"),
("look in the eyes","～の目を正視する"),
("lose one's temper","冷静さを失う；腹を立てる"),
("make both ends meet","収入内でやりくりする"),
("make a fool of","～を笑いものにする"),
("make much of","～を重要視する；【否定文で】～を理解する"),
("nothing short of","まさしく～（の）"),
("of late","近ごろ；最近"),
("off [wide of] the mark","（発言などが）的はずれの［で］"),
("on terms with A","Aと～の関係で"),
("on a diet","ダイエット中の［で］"),
("on occasion","ときどき"),
("on second thought","考え直してみて"),
("on the side","～気味で［の］"),
("on the dot","時間ちょうどに；きっかりに"),
("on the face of it","見たところは；表面上は"),
("on the tip of one's tongue","（名前などが）のどまで出かかっているが思い出せない"),
("on the verge of","～の瀬戸際で；～しそうで"),
("once and for all","きっぱりと；これを最後に"),
("one of these days","そのうちに"),
("only too","とても；大いに／遺憾［残念］ながら...だ"),
("out of breath","息切れして"),
("out of work","失業中で"),
("pay a visit to","（～を）訪問する"),
("play a trick on one","（人に）（悪意のない）いたずらをする"),
("present oneself","現れる；出頭する"),
("put to use","～を利用する"),
("put an end to","～を終わらせる"),
("quite a few","かなりの数の～"),
("right as rain","すっかり健康になって"),
("scores of","多数の～"),
("see [do] the sights of","（～の）観光をする"),
("see much of","（人）にたびたび会う"),
("so much for","～はこれでおしまい；～はそんなところ"),
("something of a","ちょっとした～；ある程度の～"),
("take by surprise","～を驚かす；～の不意を打つ"),
("take into account","～を考慮に入れる"),
("take hold of","～をつかむ；～を捕まえる"),
("take notice of","～に注意［注目］する；～に気づく"),
("take pains","骨を折る；努力する"),
("take turns","交代する"),
("the other way around [round]","あべこべに；逆に"),
("to A's advantage","Aに有利な［に］"),
("to one's heart's content","十分に；心ゆくまで"),
("to the best of one's knowledge","（人）の知る限り（では）"),
("to the effect that","...という趣旨の［で］"),
("to the full","十分に；心ゆくまで"),
("under construction","建築中で；工事中で"),
("under way","（計画などが）進行中で"),
("with ease","容易に");